<div align="center">
  <a href="https://colab.research.google.com/drive/1oWbkAtQzkIyM8T_OidY3JPmQtHP58RDt?usp=sharing" target="_parent">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
  </a>
</div>

#   Pytorch

#### The command **`import torch`**
Is the standard way to bring the PyTorch library into your Python environment. Although the framework is widely known as "PyTorch," it is **namespaced simply as `torch`** in code.

This naming choice exists largely for **historical reasons**,. The original version of the library was written in the Lua programming language and was called **Torch**; PyTorch is the modern, Python-based reimagination of that original library.

Once imported, this module gives you access to the entire **PyTorch Core ecosystem**, including its specialized data structures (tensors) and its automatic differentiation engine (`autograd`). In environments like Google Colab, importing the library is seamless because it comes pre-installed, sparing you the "headache" of manually setting up complex **NVIDIA or CUDA drivers**.

In [ ]:
import torch

#### The code `x = torch.arange(60)`
 Uses a **tensor generator function** in PyTorch that mirrors the behavior of Python’s built-in `range()` or NumPy's `arange()`.

 It creates a **rank 1 (one-dimensional)** tensor containing a sequence of 60 integers, specifically the values from **0 to 59**.

  By following this command with simply `x`, the environment—such as Google Colab—will **print the tensor’s contents and shape**, allowing you to verify that it is a single, long vector of data before you perform further operations like reshaping.
  
  ---



In [2]:
x = torch.arange(60)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59])

#### The property **`x.shape`**
Is used to reveal the **geometry of a tensor** by returning a list that contains the size of each of its axes or dimensions,. For the code            `x = torch.arange(60)`, calling `x.shape` would show that it is a **rank 1 tensor** with a single axis of size 60,.

In PyTorch, `tensor.shape` is described as the **most useful tool for debugging**,. This is because complex deep learning operations, such as **matrix multiplications, dot products, and cross products**, require the shapes of the participating tensors to align perfectly; if they do not, the code will trigger an error,.

Additionally, the shape provides a convenient way to determine a tensor's **rank** (also known as order or degree), which is simply the **length of the shape**,. While the word "dimension" can be ambiguous—sometimes referring to the rank and sometimes to the size of an axis—checking the shape allows you to see exactly how many elements exist along each specific axis.

In [3]:
x.shape

torch.Size([60])

#### The **`reshape((3,4,5))`** function
 In PyTorch takes the existing tensor—in this case, the 60 elements stored in `x`—and rearranges them into a new geometry without altering the underlying data,. This command specifically transforms the flat, one-dimensional vector into a **rank 3 tensor**, which is defined in code as having a shape with a length of three.

Geometrically, this new shape can be visualized as a **cube of data** with a depth of 3, a height of 4, and a width of 5. Alternatively, you can think of this structure as being decomposed into **three distinct "slices,"** where each slice is a **4x5 matrix**. This ability to re-mold tensors is a fundamental step in preparing data for various deep learning architectures, such as those used for image processing.

For a reshape operation to be successful, the **total number of elements must remain identical**; since 3 multiplied by 4 multiplied by 5 equals exactly 60, the operation is valid. If you were to attempt to reshape these 60 elements into a geometry that required more or fewer values, PyTorch would trigger an **error** to signal that the shapes are incompatible.

In [4]:
x.reshape((3,4,5))

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

#### The command `x = torch.arange(600)`
Uses a PyTorch generator function to create a **rank 1 tensor** containing a sequence of 600 integers,. Similar to Python's `range()`, it generates values starting from **0 up to 599**,.

This operation produces a single, long one-dimensional array. While simple, this sequence provides the necessary raw data to later be **reshaped** into more complex geometries, such as matrices or cubes, for deep learning tasks.

By typing `x` on the next line, you instruct your coding environment to **print the tensor's contents**. This allows you to quickly inspect the data and verify its structure before performing further operations,.

In [5]:
x = torch.arange(600)
x

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [7]:
torch.Size([600])

torch.Size([600])

#### The command **`x.reshape((3, 4, 5, 10))`**
Takes the 600 elements from the original tensor and rearranges them into a new, complex geometry. This transformation is valid because the total number of elements remains identical; the product of 3, 4, 5, and 10 equals exactly 600.

This operation creates a **rank 4 tensor** because the resulting shape has a length of four. While a rank 3 tensor can be visualized as a cube of data, adding a fourth axis allows for even more layers of organization, which is common when handling batches of images or complex data structures in deep learning.

As you increase the complexity of your tensors, checking the **`.shape`** property remains your most essential tool for debugging. In deep learning, if these multidimensional shapes do not align perfectly during operations like matrix multiplication, the code will fail.

In [6]:
x.reshape((3,4,5,10))

tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
          [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
          [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

         [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
          [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
          [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
          [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
          [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
          [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

         [[150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
  

<div align="center">
  <img src="../../images/PyTorchandtheDeepLearningEcosystem/tensor_visualization.png" width="400" alt="Tensor Visualization">
  <p style="text-align: center;"><b>Visualization of Tensor (3, 4, 5, 10)</b></p>
</div>

In [8]:
x.reshape((3,4,5,10)).shape

torch.Size([3, 4, 5, 10])

In [9]:
x.shape

torch.Size([600])

#### The code **`print(f"x is a rank {len(x.shape)} tensor.")`**
 Is a programmatic way to identify and display a tensor's **rank**, which is also referred to as its order or degree. In PyTorch, the rank is strictly defined as the **length of the tensor's shape**; for example, if a shape has four values like `(3, 4, 5, 10)`, its rank is 4.

This command is particularly useful for verifying the complexity of your data at a glance. While a simple vector is rank 1, more sophisticated structures—such as those used for images or large batches of data—can quickly scale to **rank 3, rank 4, or higher** as you add more axes of information.

Using the **`.shape`** property in this manner is the most essential tool for **debugging** your code. In deep learning, operations like matrix multiplications and dot products require the ranks and dimensions of tensors to align perfectly, and printing this information helps ensure your data is compatible with your model.

In [13]:
print(f"x is a rank {len(x.shape)} tensor.")

x is a rank 1 tensor.


In [15]:
y = x.reshape((3, 4, 5, 10))
y.shape

torch.Size([3, 4, 5, 10])

In [14]:
print(f"y is a rank {len(y.shape)} tensor.")

y is a rank 4 tensor.


#### The command **`x.numpy()`**
 Is used to transparently convert a PyTorch tensor into a standard **NumPy array**. This function is essential for passing your deep learning results into other libraries within the broader scientific Python ecosystem, such as those used for traditional data science or statistics.

Converting to a NumPy array is particularly helpful for **visualizing data** or plotting graphs of a model's learning distribution. While the basic functionality of tensors is intentionally designed to mirror NumPy, this method allows you to bridge the gap between PyTorch’s hardware-accelerated environment and standard Python plotting tools.

Once the data is in NumPy format, it no longer benefits from PyTorch's specialized features like **automatic differentiation or GPU acceleration**. For this reason, `x.numpy()` is typically used as a final step to inspect, debug, or present the outputs generated by your neural network.

In [17]:
x.numpy()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [20]:
x.numpy().shape

(600,)

In [18]:
y.numpy()

array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

        [[150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161

In [21]:
y.numpy().shape

(3, 4, 5, 10)